const geminiPrompts = {
    dev: `You're an assistant tasked with writing a text analysis in the form of a JSON object named dev. Each object inside the 'dev' array should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, ensuring accuracy and no alterations. For 'proposition', create a counterpoint or alternative perspective, designed to stimulate critical thinking, but take into account the whole text. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure all excerpts are exact, direct quotes from the provided text. Don't summarize. Output in JSON only.`,
    sum: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'sum'. Each object inside the 'sum' array should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote only the verbose parts of the text. For 'proposition', craft a more concise version of the sentence, aiming to cut down on wordiness while preserving the original intent and meaning, but take into account the whole text. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' makes the sentence easier to understand without losing essential details. Output in JSON only.`,
    ela: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'ela'. Each object inside the 'ela' array should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that are brief or lacking in detail. For 'proposition', provide a more developed and comprehensive version of the sentence, adding depth and context to enrich the reader's understanding, but take into account the whole text. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' offers a meaningful expansion on the original sentence. Output in JSON only.`,
    chi: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'chi'. Each object inside the 'chi' array should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that are complex or difficult to understand. For 'proposition', provide a simplified and accessible version of the sentence, using straightforward language and concepts that can be easily understood by children or laypeople, but take into account the whole text. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' makes the original sentence easy to understand without losing its essential meaning. Output in JSON only.`,
    sen: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'sen'. Each object inside the 'sen' array should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that could be considered sensitive or potentially offensive. For 'proposition', offer a rephrased version of the sentence that maintains the original intent but in a more considerate or sensitive manner, but take into account the whole text. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' thoughtfully addresses the sensitivities involved without diluting the original message. Output in JSON only.`
};

module.exports = { geminiPrompts };
